# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-02 22:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0002_auto_20170501_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_text', models.TextField(verbose_name='twitter_text')),
                ('twitter_date', models.DateTimeField(verbose_name='twitter_date')),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='twitter_user')),
            ],
            options={
                'db_table': 'twitter',
            },
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
